name: macrohunter-backend

services:
  # main engine logic
  engine:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: uvicorn engine:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
      - ./mcp_servers:/app/mcp_servers
    env_file:
      - .env
  # upload menu
  scanner:
    build:
      context: ./mcp_servers
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    command: uvicorn image_scraper:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - ./backend:/app
    env_file:
      - .env

    