import { StyleSheet } from 'react-native';
import colors from './colors';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg,
  },
  app: {
    flex: 1,
    backgroundColor: colors.bg,
    position: 'relative',
  },
  'app-header': {
    flex: 1,
    flexDirection: 'row',
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 24,
    gap: 16,
    backgroundColor: colors.bg,
  },
  'panel-left': {
    flex: 1,
    maxWidth: 420,
    gap: 20,
  },
  'panel-right': {
    flex: 1,
    gap: 40,
    paddingLeft: 10,
  },
  'section-label': {
    fontFamily: 'Inter-SemiBold',
    fontSize: 12,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    color: colors.muted,
    marginBottom: 8,
  },
  'hero-text': {
    fontFamily: 'Montserrat-ExtraBold',
    fontSize: 36,
    lineHeight: 40,
    letterSpacing: -1,
    color: colors.text,
    gap: 2,
  },
  'hero-sub': {
    fontSize: 15,
    color: colors.muted,
    lineHeight: 22,
    fontFamily: 'Inter-Regular',
  },
  'temp-nav-btn': {
    alignSelf: 'flex-start',
    backgroundColor: '#0f172a',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginBottom: 8,
  },
  'temp-nav-btn-text': {
    color: colors.bg,
    fontFamily: 'Inter-SemiBold',
    fontSize: 12,
    letterSpacing: 0.3,
  },
  'calories-card': {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  'cal-display': {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 8,
    marginTop: 4,
  },
  'cal-input': {
    fontFamily: 'Inter-Bold',
    fontSize: 48,
    color: colors.text,
    width: 180,
    letterSpacing: -1,
  },
  'cal-unit': {
    fontFamily: 'Inter-Medium',
    fontSize: 16,
    color: colors.muted,
  },
  'cal-bar': {
    marginTop: 16,
    height: 6,
    backgroundColor: colors.surface2,
    borderRadius: 3,
    overflow: 'hidden',
  },
  'cal-bar-fill': {
    height: '100%',
    backgroundColor: colors.accent,
    borderRadius: 3,
  },
  'macros-card': {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  'macros-grid': {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    marginTop: 4,
  },
  'macro-field': {
    flex: 1,
    gap: 8,
  },
  'macro-label': {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    fontFamily: 'Inter-Medium',
    fontSize: 13,
    color: colors.text,
  },
  'macro-dot': {
    width: 8,
    height: 8,
    borderRadius: 4,
    flexShrink: 0,
  },
  'macro-input-wrap': {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 4,
  },
  'macro-num': {
    fontFamily: 'Inter-SemiBold',
    fontSize: 18,
    color: colors.text,
    flex: 1,
  },
  'macro-g': {
    fontFamily: 'Inter-Medium',
    fontSize: 14,
    color: colors.muted,
  },
  'macro-bars': {
    marginTop: 20,
    gap: 10,
  },
  'mbar-row': {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    fontSize: 12,
    fontFamily: 'Inter-Medium',
    color: colors.muted,
  },
  'mbar-label': {
    width: 35,
  },
  'mbar-track': {
    flex: 1,
    height: 6,
    backgroundColor: colors.surface2,
    borderRadius: 3,
    overflow: 'hidden',
  },
  'mbar-fill': {
    height: '100%',
    backgroundColor: colors.accent,
    borderRadius: 3,
  },
  'mbar-val': {
    width: 35,
    textAlign: 'right',
  },
  'location-card': {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingHorizontal: 20,
    paddingVertical: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  acquiring: {
    borderColor: colors.accent,
    backgroundColor: '#d1fae5',
  },
  denied: {
    borderColor: '#ef4444',
    backgroundColor: '#fef2f2',
  },
  'loc-icon': {
    width: 36,
    height: 36,
    backgroundColor: colors.surface2,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  'loc-text': {
    flex: 1,
  },
  'loc-name': {
    fontFamily: 'Inter-SemiBold',
    fontSize: 14,
    color: colors.text,
  },
  'loc-coords': {
    fontSize: 13,
    color: colors.muted,
    marginTop: 2,
  },
  'search-btn': {
    width: '100%',
    paddingVertical: 16,
    paddingHorizontal: 16,
    backgroundColor: colors.accent,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  loading: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    shadowOpacity: 0,
    elevation: 0,
  },
  'btn-shimmer': {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: colors.surface,
  },
  spin: {
    fontSize: 16,
  },
  'results-header': {
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-around',
    marginTop: -10,
    marginBottom: 4,
  },
  'results-title': {
    fontFamily: 'Inter-Bold',
    fontSize: 24,
    letterSpacing: -0.5,
    color: colors.text,
  },
  'results-count': {
    fontSize: 14,
    color: colors.muted,
    fontFamily: 'Inter-Medium',
    marginBottom: 4,
  },
  'results-list': {
    gap: 12,
  },
  'result-card': {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    paddingHorizontal: 20,
    paddingVertical: 18,
    gap: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  'top-pick': {
    borderColor: colors.accent,
  },
  'top-badge': {
    alignSelf: 'flex-start',
    backgroundColor: colors.accent,
    color: colors.bg,
    fontFamily: 'Inter-SemiBold',
    fontSize: 11,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  'result-name': {
    fontFamily: 'Inter-SemiBold',
    fontSize: 16,
    color: colors.text,
    marginBottom: 6,
  },
  'result-meta': {
    fontSize: 13,
    color: colors.muted,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
  },
  'result-meta-sep': {
    color: '#cbd5e1',
  },
  'result-macros': {
    flexDirection: 'row',
    gap: 16,
  },
  rmacro: {
    gap: 2,
  },
  'rmacro-label': {
    fontSize: 22,
    fontFamily: 'Inter-Medium',
    color: colors.muted,
  },
  'rmacro-val': {
    fontFamily: 'Inter-SemiBold',
    fontSize: 20,
  },
  'result-right': {
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: 10,
  },
  'result-cal': {
    fontFamily: 'Inter-Bold',
    fontSize: 28,
    lineHeight: 28,
    color: colors.text,
  },
  'result-cal-unit': {
    fontSize: 12,
    color: colors.muted,
    fontFamily: 'Inter-Medium',
    marginTop: 2,
  },
  'result-score': {
    fontFamily: 'Inter-SemiBold',
    fontSize: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  'score-high': {
    color: '#065f46',
    backgroundColor: '#d1fae5',
  },
  'score-mid': {
    color: '#854d0e',
    backgroundColor: '#fef08a',
  },
  'score-low': {
    color: colors.muted,
    backgroundColor: colors.surface2,
  },
  'empty-state': {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    paddingVertical: 60,
  },
  'empty-icon': {
    width: 64,
    height: 64,
    backgroundColor: colors.surface2,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  'empty-text': {
    fontFamily: 'Inter-SemiBold',
    fontSize: 18,
    color: colors.text,
  },
  'empty-sub': {
    fontSize: 14,
    color: colors.muted,
    textAlign: 'center',
    maxWidth: 280,
    lineHeight: 20,
  },
  'skeleton-card': {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 16,
    paddingHorizontal: 20,
    paddingVertical: 18,
  },
  'skel-line': {
    backgroundColor: colors.surface2,
    borderRadius: 4,
    marginBottom: 10,
  },
  'lb-overlay': {
    ...StyleSheet.absoluteFillObject,
    zIndex: 1000,
    backgroundColor: 'rgba(0,0,0,0.8)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
  },
  'lb-card': {
    backgroundColor: colors.surface,
    borderRadius: 24,
    width: '90%',
    maxWidth: 560,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.18,
    shadowRadius: 30,
    elevation: 8,
  },
  'lb-close': {
    position: 'absolute',
    top: 16,
    right: 16,
    zIndex: 10,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(0,0,0,0.35)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  'lb-image-wrap': {
    width: '100%',
    height: 220,
    backgroundColor: colors.surface2,
    position: 'relative',
  },
  'lb-image-placeholder': {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: '#e8f0fe',
  },
  'lb-top-badge': {
    position: 'absolute',
    top: 16,
    left: 16,
    backgroundColor: colors.accent,
    color: colors.bg,
    fontFamily: 'Inter-SemiBold',
    fontSize: 11,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 999,
  },
  'lb-body': {
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 20,
  },
  'lb-restaurant': {
    fontSize: 12,
    fontFamily: 'Inter-SemiBold',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    color: colors.accent,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 6,
  },
  'lb-title': {
    fontFamily: 'Inter-Bold',
    fontSize: 20,
    color: colors.text,
    lineHeight: 26,
    marginBottom: 4,
  },
  'lb-status-row': {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    fontSize: 13,
    color: colors.muted,
    marginBottom: 20,
  },
  'lb-cal-row': {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 6,
    marginBottom: 20,
  },
  'lb-cal-num': {
    fontFamily: 'Montserrat-ExtraBold',
    fontSize: 40,
    letterSpacing: -1.5,
    color: colors.text,
    lineHeight: 40,
  },
  'lb-cal-unit': {
    fontFamily: 'Inter-Medium',
    fontSize: 14,
    color: colors.muted,
  },
  'lb-macros': {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 20,
  },
  'lb-macro': {
    flex: 1,
    backgroundColor: colors.surface2,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 4,
  },
  'lb-macro-label': {
    fontSize: 11,
    fontFamily: 'Inter-SemiBold',
    color: colors.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  'lb-macro-val': {
    fontFamily: 'Inter-Bold',
    fontSize: 18,
  },
  'lb-divider': {
    height: 1,
    backgroundColor: '#e2e8f0',
    marginBottom: 20,
  },
  'lb-Viewider': {
    height: 1,
    backgroundColor: '#e2e8f0',
    marginBottom: 20,
  },
  'lb-price-row': {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  'lb-price-label': {
    fontSize: 13,
    color: colors.muted,
    fontFamily: 'Inter-Medium',
  },
  'lb-price-val': {
    fontFamily: 'Inter-Bold',
    fontSize: 22,
    color: colors.text,
    letterSpacing: -0.5,
  },
  'lb-actions': {
    flexDirection: 'row',
    gap: 10,
  },
  'lb-directions-btn': {
    flex: 1,
    paddingVertical: 14,
    paddingHorizontal: 20,
    backgroundColor: colors.accent,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 2,
  },
  'lb-score-chip': {
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface2,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    minWidth: 80,
  },
  'lb-score-num': {
    fontFamily: 'Montserrat-ExtraBold',
    fontSize: 18,
    color: colors.text,
    lineHeight: 18,
  },
  'lb-score-label': {
    fontSize: 10,
    fontFamily: 'Inter-SemiBold',
    color: colors.muted,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
});

export default styles;
