name: Daily Caching

on:
  schedule:
    - cron: '0 7 * * *'  # 3 AM EDT / 7 AM UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    env:
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      FATSECRET_CLIENT_ID: ${{ secrets.FATSECRET_CLIENT_ID }}
      FATSECRET_CLIENT_SECRET: ${{ secrets.FATSECRET_CLIENT_SECRET }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      USDA_API_KEY: ${{ secrets.USDA_API_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python scripts/caching-script.py